# Generated by Django 4.2.13 on 2024-07-20 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
