# Generated by Django 4.2.13 on 2024-07-20 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
