# Generated by Django 4.2.13 on 2024-07-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name_product',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
