# Generated by Django 4.2.13 on 2024-07-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_order_name_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name_product',
        ),
    ]
