# Generated by Django 4.2.13 on 2024-07-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_order_product_remove_order_cart_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
