# Generated by Django 4.2.13 on 2024-07-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.JSONField(default={'100': '100', '105': '105', '110': '110', '115': '115', '120': '120', '125': '125', '130': '130'}, verbose_name='Размер'),
        ),
    ]
